# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7c4d55b23a53abb8e4b14122b353e6fc"
name = "jetcredit"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_app_proxy,write_customers,write_orders,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
url = "/proxy"
subpath = "jetcredit"
prefix = "apps"
